ort:
  enableRepositoryPackageCurations: true
  forceOverwrite: true

  scanner:
    skipConcluded: false
    includeFilesWithoutFindings: true

  analyzer:
    allowDynamicVersions: true
    enabledPackageManagers: [Unmanaged, SpdxDocumentFile]
    # A flag to control whether excluded scopes and paths should be skipped during the analysis.
    skipExcluded: true
